language: python
cache: apt
sudo: false
branches:
  only:
  - master
python:
- 3.6

install:
- pip install -U --upgrade-strategy=eager 'Nikola[extras]'

script:
  - nikola build

deploy:
  provider: script
  script: chmod +x deploy.sh
  skip_cleanup: true
